services:
  db:
    image: cockroachdb/cockroach:v23.1.13
    command: start --insecure --advertise-addr=${NODE_IP:-db} --join=${JOIN_IPS:-db} --http-addr=0.0.0.0
    ports:
      - "5196:26257"   # IBP DB Port
      - "8099:8080"    # DB Console
    volumes:
      - cockroach_data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 5s
      retries: 5

  vault:
    image: hashicorp/vault:1.13.3
    restart: always
    network_mode: "host"
    volumes:
      - ./vault/config:/vault/config:ro
      - ./vault/data:/vault/data
    command: server
    cap_add:
      - IPC_LOCK

  gateway:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"      # Standard HTTP Port for Flexible SSL
      - "443:443"    # Secure Mesh Port (HTTPS)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./web:/usr/share/nginx/html:ro

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiYzA3Y2NjYTM3ZDMyN2Y3Nzk5NjcxZDIzMDhmODBiZWIiLCJ0IjoiNzUzMDQ5NzAtMWZhMC00Y2Q0LTg1M2QtOGUzZGQyM2NjOGU0IiwicyI6IlpqTTFNRFkzTUdZdE9ESTFZaTAwT1RNM0xXRmtORFl0Wm1Fd01UQXdOR1l3T1dVeiJ9
    restart: always
    depends_on:
      - gateway

  imagefx:
    build: ./imagefx
    restart: always
    environment:
      - GEMINI_API_KEY=AIzaSyCjwR9Y9pN7d033p5Fbwq1yN1tyTacfqjM
    volumes:
      - ./imagefx/media:/app/media

volumes:
  cockroach_data:
